spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always
    data: classpath:data.sql
    driverClassName: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    mongodb:
      uri: mongodb://localhost
      port: 27017
      database: springBatchMongo

#  jpa:
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: false

#logging:
#  level:
#    ROOT: ERROR