spring:
  datasource:
    url: jdbc:h2:mem:testdb
    initialization-mode: always

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
        format_sql: false

  jmx:
    enabled: true

logging:
  level:
    ROOT: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss}[%thread]%-5level %logger{36} - %msg%n"
  file:
    name: "application.log"

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,loggers
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true