version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    privileged: true
    ports:
      - "8080:8080"
    environment:
      - WAIT_FOR=mongodb:27017
    networks:
      - nw
  mongodb:
      image: mongo:latest
      container_name: "mongodb"
      volumes:
        - ./data/db:/data/db
      ports:
        - 27017:27017
      networks:
        - nw
networks:
  nw: