DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID IDENTITY PRIMARY KEY, NAME VARCHAR (255));

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR(ID IDENTITY PRIMARY KEY, BOOK_ID BIGINT,AUTHOR_ID BIGINT);
CREATE UNIQUE INDEX IF NOT EXISTS BOOK_AUTHOR_U2 ON BOOK_AUTHOR(BOOK_ID,AUTHOR_ID);
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE;
ALTER TABLE BOOK_AUTHOR ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE;

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK_CATEGORY;
CREATE TABLE BOOK_CATEGORY(ID IDENTITY PRIMARY KEY, BOOK_ID BIGINT,CATEGORY_ID BIGINT);
CREATE UNIQUE INDEX IF NOT EXISTS BOOK_CATEGORY_U2 ON BOOK_CATEGORY(BOOK_ID,CATEGORY_ID);
ALTER TABLE BOOK_CATEGORY ADD FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE;
ALTER TABLE BOOK_CATEGORY ADD FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID) ON DELETE CASCADE;