DROP TABLE IF EXISTS BOOK;
CREATE TABLE BOOK(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID IDENTITY PRIMARY KEY, NAME VARCHAR (255));

DROP TABLE IF EXISTS BOOK_AUTHOR;
CREATE TABLE BOOK_AUTHOR(ID IDENTITY PRIMARY KEY, BOOK_ID BIGINT,AUTHOR_ID BIGINT);
CREATE UNIQUE INDEX IF NOT EXISTS BOOK_AUTHOR_U2 ON BOOK_AUTHOR(BOOK_ID,AUTHOR_ID);

DROP TABLE IF EXISTS CATEGORY;
CREATE TABLE CATEGORY(ID IDENTITY PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOK_CATEGORY;
CREATE TABLE BOOK_CATEGORY(ID IDENTITY PRIMARY KEY, BOOK_ID BIGINT,CATEGORY_ID BIGINT);
CREATE UNIQUE INDEX IF NOT EXISTS BOOK_CATEGORY_U2 ON BOOK_CATEGORY(BOOK_ID,CATEGORY_ID);